%%
%% Autogenerated by Thrift Compiler (0.8.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(srv_thrift).
-behaviour(thrift_service).


-include("srv_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info('i am a dummy struct') -> undefined.
%%% interface
% Janky(This, Arg)
function_info('Janky', params_type) ->
{struct, [{1, i32}]}
;
function_info('Janky', reply_type) ->
i32;
function_info('Janky', exceptions) ->
{struct, []}
;
% voidMethod(This)
function_info('voidMethod', params_type) ->
{struct, []}
;
function_info('voidMethod', reply_type) ->
{struct, []};
function_info('voidMethod', exceptions) ->
{struct, []}
;
% primitiveMethod(This)
function_info('primitiveMethod', params_type) ->
{struct, []}
;
function_info('primitiveMethod', reply_type) ->
i32;
function_info('primitiveMethod', exceptions) ->
{struct, []}
;
% structMethod(This)
function_info('structMethod', params_type) ->
{struct, []}
;
function_info('structMethod', reply_type) ->
{struct, {'debugProtoTest_types', 'compactProtoTestStruct'}};
function_info('structMethod', exceptions) ->
{struct, []}
;
% methodWithDefaultArgs(This, Something)
function_info('methodWithDefaultArgs', params_type) ->
{struct, [{1, i32}]}
;
function_info('methodWithDefaultArgs', reply_type) ->
{struct, []};
function_info('methodWithDefaultArgs', exceptions) ->
{struct, []}
;
% onewayMethod(This)
function_info('onewayMethod', params_type) ->
{struct, []}
;
function_info('onewayMethod', reply_type) ->
oneway_void;
function_info('onewayMethod', exceptions) ->
{struct, []}
;
function_info(_Func, _Info) -> no_function.

